=== balabhv/CapstoneProject/gesture_data/gesture_data.dtd
<!ELEMENT gestures (gesture+) >
<!ELEMENT gesture (hand, hand)>
<!ELEMENT hand (thumb, index, middle, ring, pinky, thumb-index, index-middle, middle-ring, ring-pinky, accel)>
<!ATTLIST hand side (left | right) #REQUIRED>
<!ELEMENT thumb (flex, contact)>
<!ELEMENT index (flex, contact)>
<!ELEMENT middle (flex, contact)>
<!ELEMENT ring (flex, contact)>
<!ELEMENT pinky (flex, contact)>
<!ELEMENT thumb-index (contact)>
<!ELEMENT index-middle (contact)>
<!ELEMENT middle-ring (contact)>
<!ELEMENT ring-pinky (contact)>
<!ELEMENT accel (x, y, z)>
<!ELEMENT flex (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT z (#PCDATA)>

=== balabhv/CapstoneProject/gesture_data/gesture_data.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE gestures SYSTEM "gesture_data.dtd">
<gestures>
	<gesture>
		<hand side="left">
			<thumb>
				<flex>30</flex>
				<contact>true</contact>
			</thumb>
			<index>
				<flex>27</flex>
				<contact>false</contact>
			</index>
			<middle>
				<flex>42</flex>
				<contact>true</contact>
			</middle>
			<ring>
				<flex>33</flex>
				<contact>true</contact>
			</ring>
			<pinky>
				<flex>42</flex>
				<contact>true</contact>
			</pinky>
		</hand>
		<hand side="right">
			<thumb>
				<flex>17</flex>
				<contact>false</contact>
			</thumb>
			<index>
				<flex>10</flex>
				<contact>false</contact>
			</index>
			<middle>
				<flex>28</flex>
				<contact>false</contact>
			</middle>
			<ring>
				<flex>34</flex>
				<contact>false</contact>
			</ring>
			<pinky>
				<flex>10</flex>
				<contact>false</contact>
			</pinky>
		</hand>
	</gesture>
</gestures>

=== balabhv/CapstoneProject/microcomputer/gesture_data.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE gestures SYSTEM "gesture_data.dtd">
<gestures>
	<gesture>
		<hand side="left">
			<thumb>
				<flex>24</flex>
				<contact>true</contact>
			</thumb>
			<index>
				<flex>15</flex>
				<contact>true</contact>
			</index>
			<middle>
				<flex>32</flex>
				<contact>false</contact>
			</middle>
			<ring>
				<flex>25</flex>
				<contact>false</contact>
			</ring>
			<pinky>
				<flex>0</flex>
				<contact>false</contact>
			</pinky>
			<thumb-index>
				<contact>true</contact>
			</thumb-index>
			<index-middle>
				<contact>true</contact>
			</index-middle>
			<middle-ring>
				<contact>false</contact>
			</middle-ring>
			<ring-pinky>
				<contact>true</contact>
			</ring-pinky>
		</hand>
		<hand side="right">
			<thumb>
				<flex>10</flex>
				<contact>true</contact>
			</thumb>
			<index>
				<flex>14</flex>
				<contact>false</contact>
			</index>
			<middle>
				<flex>25</flex>
				<contact>false</contact>
			</middle>
			<ring>
				<flex>42</flex>
				<contact>true</contact>
			</ring>
			<pinky>
				<flex>34</flex>
				<contact>true</contact>
			</pinky>
			<thumb-index>
				<contact>true</contact>
			</thumb-index>
			<index-middle>
				<contact>false</contact>
			</index-middle>
			<middle-ring>
				<contact>true</contact>
			</middle-ring>
			<ring-pinky>
				<contact>false</contact>
			</ring-pinky>
		</hand>
	</gesture>
</gestures>

=== balabhv/CapstoneProject/gesture_data/alphabet_xml/gesture_data_I.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE gestures SYSTEM "gesture_data.dtd">
<gestures>
	<gesture>
		<hand side="left">
			<thumb>
				<flex>50</flex>
				<contact>true</contact>
			</thumb>
			<index>
				<flex>0</flex>
				<contact>true</contact>
			</index>
			<middle>
				<flex>0</flex>
				<contact>true</contact>
			</middle>
			<ring>
				<flex>0</flex>
				<contact>true</contact>
			</ring>
			<pinky>
				<flex>100</flex>
				<contact>false</contact>
			</pinky>
			<thumb-index>
				<contact>true</contact>
			</thumb-index>
			<index-middle>
				<contact>true</contact>
			</index-middle>
			<middle-ring>
				<contact>true</contact>
			</middle-ring>
			<ring-pinky>
				<contact>false</contact>
			</ring-pinky>
                        <accel>
			        <x>0.0</x>
			        <y>0.0</y>
			        <z>0.0</z>
                        </accel>
		</hand>
		<hand side="right">
			<thumb>
				<flex>50</flex>
				<contact>true</contact>
			</thumb>
			<index>
				<flex>0</flex>
				<contact>true</contact>
			</index>
			<middle>
				<flex>0</flex>
				<contact>true</contact>
			</middle>
			<ring>
				<flex>0</flex>
				<contact>true</contact>
			</ring>
			<pinky>
				<flex>100</flex>
				<contact>false</contact>
			</pinky>
			<thumb-index>
				<contact>true</contact>
			</thumb-index>
			<index-middle>
				<contact>true</contact>
			</index-middle>
			<middle-ring>
				<contact>true</contact>
			</middle-ring>
			<ring-pinky>
				<contact>false</contact>
			</ring-pinky>
                        <accel>
			        <x>0.0</x>
			        <y>0.0</y>
			        <z>0.0</z>
                        </accel>
		</hand>
	</gesture>
</gestures>

=== balabhv/CapstoneProject/gesture_data/alphabet_xml_prev/gesture_data_N.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE gestures SYSTEM "gesture_data.dtd">
<gestures>
	<gesture>
		<hand side="left">
			<thumb>
				<flex>0</flex>
				<contact>true</contact>
			</thumb>
			<index>
				<flex>0</flex>
				<contact>true</contact>
			</index>
			<middle>
				<flex>0</flex>
				<contact>true</contact>
			</middle>
			<ring>
				<flex>0</flex>
				<contact>true</contact>
			</ring>
			<pinky>
				<flex>0</flex>
				<contact>true</contact>
			</pinky>
			<thumb-index>
				<contact>true</contact>
			</thumb-index>
			<index-middle>
				<contact>true</contact>
			</index-middle>
			<middle-ring>
				<contact>false</contact>
			</middle-ring>
			<ring-pinky>
				<contact>true</contact>
			</ring-pinky>
                        <accel>
			        <x>0.0</x>
			        <y>0.0</y>
			        <z>0.0</z>
                        </accel>
		</hand>
		<hand side="right">
			<thumb>
				<flex>0</flex>
				<contact>true</contact>
			</thumb>
			<index>
				<flex>0</flex>
				<contact>true</contact>
			</index>
			<middle>
				<flex>0</flex>
				<contact>true</contact>
			</middle>
			<ring>
				<flex>0</flex>
				<contact>true</contact>
			</ring>
			<pinky>
				<flex>0</flex>
				<contact>true</contact>
			</pinky>
			<thumb-index>
				<contact>true</contact>
			</thumb-index>
			<index-middle>
				<contact>true</contact>
			</index-middle>
			<middle-ring>
				<contact>false</contact>
			</middle-ring>
			<ring-pinky>
				<contact>true</contact>
			</ring-pinky>
                        <accel>
			        <x>0.0</x>
			        <y>0.0</y>
			        <z>0.0</z>
                        </accel>
		</hand>
	</gesture>
        <converted-text></converted-text>
	<status>disconnected</status>
	<convert>false</convert>
	<version>1.0</version>
</gestures>

=== balabhv/CapstoneProject/gesture_data/numbers_xml_prev/gesture_data_4.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE gestures SYSTEM "gesture_data.dtd">
<gestures>
	<gesture>
		<hand side="left">
			<thumb>
				<flex>0</flex>
				<contact>false</contact>
			</thumb>
			<index>
				<flex>100</flex>
				<contact>false</contact>
			</index>
			<middle>
				<flex>100</flex>
				<contact>false</contact>
			</middle>
			<ring>
				<flex>100</flex>
				<contact>false</contact>
			</ring>
			<pinky>
				<flex>100</flex>
				<contact>false</contact>
			</pinky>
			<thumb-index>
				<contact>true</contact>
			</thumb-index>
			<index-middle>
				<contact>false</contact>
			</index-middle>
			<middle-ring>
				<contact>false</contact>
			</middle-ring>
			<ring-pinky>
				<contact>false</contact>
			</ring-pinky>
                        <accel>
			        <x>0.0</x>
			        <y>0.0</y>
			        <z>0.0</z>
                        </accel>
		</hand>
		<hand side="right">
			<thumb>
				<flex>0</flex>
				<contact>false</contact>
			</thumb>
			<index>
				<flex>100</flex>
				<contact>false</contact>
			</index>
			<middle>
				<flex>100</flex>
				<contact>false</contact>
			</middle>
			<ring>
				<flex>100</flex>
				<contact>false</contact>
			</ring>
			<pinky>
				<flex>100</flex>
				<contact>false</contact>
			</pinky>
			<thumb-index>
				<contact>true</contact>
			</thumb-index>
			<index-middle>
				<contact>false</contact>
			</index-middle>
			<middle-ring>
				<contact>false</contact>
			</middle-ring>
			<ring-pinky>
				<contact>false</contact>
			</ring-pinky>
                        <accel>
			        <x>0.0</x>
			        <y>0.0</y>
			        <z>0.0</z>
                        </accel>
		</hand>
	</gesture>
</gestures>
